### ISSUE TITLE
Use of sp_MSforeachtable on Azure SQL Database

### ISSUE THREAD

**Issue by meet-bhagdev** [aaugustin/django-pymssql#12]
Hi Aymeric,
Hope you are doing well. I am working on a Django app that uses django-pymssql. It works great on SQL Server, however if I try to run the same app with my Azure SQL Database it fails.

It is because the stored proc - sp_MSforeachtable is not supported on Azure SQL Database. 

Here is my error message when I run python manage.py migrate:

File "/Library/Python/2.7/site-packages/sqlserver_ado/base.py", line 292, in disable_constraint_checking
    cursor.execute('EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"')
  File "pymssql.pyx", line 462, in pymssql.Cursor.execute (pymssql.c:6514)
pymssql.ProgrammingError: (2812, "Could not find stored procedure 'sp_MSforeachtable'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

What would be your recommendation in getting migrations to work for Azure SQL Database the same as SQL Server. As of now, my work around is using SSMS to create the stored proc so that django-pymssql can use it. However, for a pure linux/mac environment that will be difficult.

Please let me know.

Thanks,
Meet

**Comment by aaugustin** [comment]
Hi Meet,

The stack trace shows that the code initiating the call to this stored procedure is in `sqlserver_ado/base.py`, a module provided by django-mssql:

- https://bitbucket.org/Manfre/django-mssql/src/bf1a60b3dab6c89c72e71211988354d3f981bc47/sqlserver_ado/base.py?at=master&fileviewer=file-view-default#base.py-292
- https://bitbucket.org/Manfre/django-mssql/src/bf1a60b3dab6c89c72e71211988354d3f981bc47/sqlserver_ado/base.py?at=master&fileviewer=file-view-default#base.py-304

Obviously the same problem happens with plain django-mssql on Windows, without django-pymssql. I suggest to head over to the django-mssql repository to have this discussion.
