### ISSUE TITLE
django-pymssql and "Always Encrypted" feature of MS SQL Server 2016 Enterprise

### ISSUE THREAD

**Issue by syguts** [aaugustin/django-pymssql#15]
MS SQL Server 2016 Enterprise introduced "Always Encrypted" feature
https://msdn.microsoft.com/en-us/library/mt163865.aspx.

Is there a plan to support it in django-pymssql?

**Comment by aaugustin** [comment]
I'm no longer working with SQL Server and I'm unlikely to maintain this library going forward.

It's possible that, if pymssql supports it, you can simply configure this in connection `OPTIONS`.
