### ISSUE TITLE
table with schema reference

### ISSUE THREAD

**Issue by omargiorgetti** [aaugustin/django-pymssql#2]
Hi, I'm using pymssql from a django framework on centos7 on viirtualbox to Ms SqlServer 2008 R2 Express. I'm using the meta instrtuction like db_table=schema].[table.
When django generate the sql create a "create index" statement with name the schema and  table separated with point. That's the generated error "django.db.utils.ProgrammingError: (102, "Incorrect syntax near '.'.DB-Lib error message 20018,".

**Comment by manfre** [comment]
This may or may not be a pymssql specific error, but relying upon "schema].[table" is not recommended or officially supported by django-mssql.

**Comment by aaugustin** [comment]
Yes, that's a hack and I have little interest in researching a way to support it. If you have a patch I'll look into it. However I suspect it will be a patch for pymssql or django-mssql. django-pymssql is a very small bridge; these libraries do all the heavy lifting.
