### ISSUE TITLE
pip install assumes django-mssql 2.x.x -- that's bad for SQL2005/8

### ISSUE THREAD

**Issue by erikvw** [aaugustin/django-pymssql#8]
this package wraps `django-mssql`. the README says it was tested on `django-mssql` 1.6.x and MSSQL 2012 but should work on 2005/8. If you just `pip install django-pymssql`, the most recent version of `django-mssql` installs (2.x.x) . However, 2.x.x does not support MSSQL 2005/8, 1.6.x does. It would be helpful to add a comment to clarify this to the README as well as to specify the version in `setup.py` and/or add a `requirements.txt`. Something as simple as:

Note: MSSQL 2005/8 requires django-mssql 1.6.x

**Comment by aaugustin** [comment]
Yes, that makes sense. django-mssql 2.x.x didn't exist when I wrote that sentence.

**Comment by manfre** [comment]
django-mssql 2.x.x still doesn't exist. The latest stable release is 1.7. Django-mssql 1.8 will have a beta release very soon. The published version's MAJOR.MINOR will match the Django version it supports.

**Comment by erikvw** [comment]
my mistake. django-mssql 1.7.x does not work for MSSQL 2005, not 2.x.x. I
noticed in your change log for version 1.6 it states 2005 is no longer
supported and at https://bitbucket.org/Manfre/django-mssql you state "SQL
2008/2008r2 are support by django-mssql 1.6.x.". 1.6.x seems to work for
accessing my 2005 server so far but I am querying only. The main issue was
with the use of *OFFSET*/*FETCH* for slicing. thanks

**Comment by manfre** [comment]
I don't think I removed all of the special logic for SQL Server 2005 from django-mssql 1.6; it mostly involved microseconds. The dropped support statement in that release was to notify that I don't test it anymore and won't fix any issues that crop up. Slicing and things involving the date/time data types are where things are likely to not work between different versions of django-mssql.

**Comment by aaugustin** [comment]
I'm going to close this issue because I don't see any action to be taken in django-pymssql. Let me know if I missed something.
